#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x fcitx5 > /dev/null || fcitx5 &

pgrep -x xautolock > /dev/null || xautolock -time 10  -locker lock.sh &

pgrep -x blueman-applet > /dev/null || blueman-applet &

pgrep -x dunst > /dev/null || dunst &

pgrep -x qv2ray > /dev/null || qv2ray &

pgrep -x variety > /dev/null || variety &

pgrep -x nm-applet > /dev/null || nm-applet &

$HOME/.config/polybar/launch.sh --shades

$HOME/.local/bin/desktop_floating &

wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Oblogout state=floating follow=on
bspc rule -a jetbrains-clion desktop='^5' state=floating follow=on
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a Alacritty desktop='^2' follow=on
